site_name: PyLab
site_url: https://anzchy.github.io/pylaboratory
nav:
  - Home: index.md
  - Tutorials:
      - Hello World: tutorial/01_intro.md
      - Snippet Demo: tutorial/02_snippet_demo.md
theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - toc.follow
    - content.tooltips
plugins:
  - search
  - macros:
      module_name: macros/pylab_macros
extra_javascript:
  - assets/js/pylab-editor.js
  - assets/js/init.js
